package dev.prateekthakur.devprobe.presentation.theme

import androidx.compose.ui.graphics.Color

// Brand palette: a single Android-green hue, monochromatic across all three tonal
// roles (primary = vivid accent, secondary = muted/low-chroma, tertiary = a deeper
// tonal step) — no unrelated hues (indigo/teal/amber) mixed in.
val PrimaryLight = Color(0xFF146C2E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFA6F6B4)
val OnPrimaryContainerLight = Color(0xFF002106)
val SecondaryLight = Color(0xFF52634F)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD5E8CE)
val OnSecondaryContainerLight = Color(0xFF101F0F)
val TertiaryLight = Color(0xFF33691E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFB6F397)
val OnTertiaryContainerLight = Color(0xFF0B2000)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAF8FF)
val OnBackgroundLight = Color(0xFF1A1B22)
val SurfaceLight = Color(0xFFFAF8FF)
val OnSurfaceLight = Color(0xFF1A1B22)
val SurfaceVariantLight = Color(0xFFE2E1EC)
val OnSurfaceVariantLight = Color(0xFF45464F)
val OutlineLight = Color(0xFF767680)
val OutlineVariantLight = Color(0xFFC6C5D0)
val SurfaceContainerLowLight = Color(0xFFF3F2FA)
val SurfaceContainerLight = Color(0xFFEDECF5)
val SurfaceContainerHighLight = Color(0xFFE8E6EF)
val SurfaceContainerHighestLight = Color(0xFFE2E1EA)

val PrimaryDark = Color(0xFF8BD692)
val OnPrimaryDark = Color(0xFF00391A)
val PrimaryContainerDark = Color(0xFF00522A)
val OnPrimaryContainerDark = Color(0xFFA6F6B4)
val SecondaryDark = Color(0xFFB9CCB2)
val OnSecondaryDark = Color(0xFF243424)
val SecondaryContainerDark = Color(0xFF3A4A38)
val OnSecondaryContainerDark = Color(0xFFD5E8CE)
val TertiaryDark = Color(0xFF98D67F)
val OnTertiaryDark = Color(0xFF0B3900)
val TertiaryContainerDark = Color(0xFF1D5000)
val OnTertiaryContainerDark = Color(0xFFB6F397)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF121318)
val OnBackgroundDark = Color(0xFFE3E2EA)
val SurfaceDark = Color(0xFF121318)
val OnSurfaceDark = Color(0xFFE3E2EA)
val SurfaceVariantDark = Color(0xFF45464F)
val OnSurfaceVariantDark = Color(0xFFC6C5D0)
val OutlineDark = Color(0xFF90909A)
val OutlineVariantDark = Color(0xFF45464F)
val SurfaceContainerLowDark = Color(0xFF1A1B21)
val SurfaceContainerDark = Color(0xFF1E1F25)
val SurfaceContainerHighDark = Color(0xFF282930)
val SurfaceContainerHighestDark = Color(0xFF33343B)

// Severity accents, shared by SeverityBadge/FindingCard — kept independent of the
// Material tonal roles so severity meaning stays legible in both themes.
val SeverityCritical = Color(0xFFC5231F)
val SeverityHigh = Color(0xFFE0554F)
val SeverityMedium = Color(0xFFE8973D)
val SeverityLow = Color(0xFF3D7FE0)
val SeverityInfo = Color(0xFF7A8194)
val OnSeverityColor = Color(0xFFFFFFFF)
